/** @format */

"use client";
/** @format */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Component/Navbar";
import { Provider } from "react-redux";
import { store } from "../../store/store";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Provider store={store}>
					<SessionProvider>
						<Navbar />
						{children}
					</SessionProvider>
					<Toaster />
				</Provider>
			</body>
		</html>
	);
}
